/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Dell
 */
public class Frm_Cliente_Secu extends javax.swing.JFrame {

    /**
     * Creates new form Cliente_Secu
     */
    public Frm_Cliente_Secu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        cbx_sector = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Cliente = new javax.swing.JTable();
        btn_medicina = new javax.swing.JLabel();
        btn_accesorio = new javax.swing.JLabel();
        btn_peluqueria = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_atras = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPrincipal.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbx_sector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sector" }));
        cbx_sector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_sectorActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_sector, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 190, -1));

        tabla_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_Cliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 620, 260));

        btn_medicina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clinica.png"))); // NOI18N
        btn_medicina.setToolTipText("Clinica");
        getContentPane().add(btn_medicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        btn_accesorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acesorio.png"))); // NOI18N
        btn_accesorio.setToolTipText("Accesorios");
        getContentPane().add(btn_accesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        btn_peluqueria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corte.png"))); // NOI18N
        btn_peluqueria.setToolTipText("Peluqueria");
        getContentPane().add(btn_peluqueria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Honey and Raspberries", 0, 42)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MEJOR OPCIÓN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Honey and Raspberries", 0, 42)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ElIGE TU");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maya.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 100));

        btn_atras.setFont(new java.awt.Font("Dinomik", 0, 14)); // NOI18N
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 60, -1));

        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPrincipal.png"))); // NOI18N
        getContentPane().add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel3.setText("Atras");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClienteSe.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 710, 600));

        jMenu1.setText("MENU ");
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_sectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_sectorActionPerformed
        System.out.println("no molestes");
    }//GEN-LAST:event_cbx_sectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Cliente_Secu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Cliente_Secu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Cliente_Secu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Cliente_Secu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Cliente_Secu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_accesorio;
    private javax.swing.JLabel btn_atras;
    private javax.swing.JLabel btn_inicio;
    private javax.swing.JLabel btn_medicina;
    private javax.swing.JLabel btn_peluqueria;
    private javax.swing.JComboBox<String> cbx_sector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_Cliente;
    // End of variables declaration//GEN-END:variables
}
