/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Dell
 */
public class Frm_Reg_Establecimeinto_Gerente extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Establecimeinto_Cliente
     */
    public Frm_Reg_Establecimeinto_Gerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_sector = new javax.swing.JTextField();
        txt_telefono_esta = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_telefono_gerente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        js_nuemro = new javax.swing.JSpinner();
        cb_accesorio = new javax.swing.JCheckBox();
        cb_peluqueria = new javax.swing.JCheckBox();
        cb_medicina = new javax.swing.JCheckBox();
        cbx_hora_apertura = new javax.swing.JComboBox<>();
        cbx_hora_apertura_numero = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        cbx_hora_cierre = new javax.swing.JComboBox<>();
        cbx_hora_cierre_numero = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_nombre_gerente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        lbl_foto = new javax.swing.JLabel();
        btn_caragarfoto = new javax.swing.JButton();
        btn_atras = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        btn_inicio = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_correo_gerente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel18.setFont(new java.awt.Font("Dinomik", 0, 14)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        jLabel18.setText("Atras");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Honey and Raspberries", 0, 40)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html> REGISTRAR<br>GERENTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel3.setText("Sector:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, -1));

        jLabel4.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel4.setText("Nombre: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel7.setText("<html>Horario de<br>apertura:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel8.setText("Logo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel9.setText("Descripcion:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel10.setText("Dirección:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 170, -1));
        getContentPane().add(txt_sector, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 170, -1));
        getContentPane().add(txt_telefono_esta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 170, -1));
        getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 140, -1));
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, -1));

        jLabel12.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel12.setText("<html>Número de<br>empleados:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));
        getContentPane().add(txt_telefono_gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 140, -1));

        jLabel13.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel13.setText("Servicios:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel15.setText("<html>Horario de<br>cierre:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel16.setText("Cédula: ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel21.setText("<html> Fecha de<br>nacimiento:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));
        getContentPane().add(js_nuemro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 70, -1));

        cb_accesorio.setText("Accesorios");
        getContentPane().add(cb_accesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        cb_peluqueria.setText("Peluqueria");
        getContentPane().add(cb_peluqueria, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 80, -1));

        cb_medicina.setText("Medicina");
        getContentPane().add(cb_medicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 70, -1));

        cbx_hora_apertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "AM", "PM" }));
        getContentPane().add(cbx_hora_apertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 60, -1));

        cbx_hora_apertura_numero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00" }));
        getContentPane().add(cbx_hora_apertura_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 230, 100));

        cbx_hora_cierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "AM", "PM" }));
        getContentPane().add(cbx_hora_cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        cbx_hora_cierre_numero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00" }));
        getContentPane().add(cbx_hora_cierre_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Honey and Raspberries", 0, 40)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html>     REGISTRAR<br>ESTABLECIMEINTO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel22.setText("Apellido: ");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, -1, -1));
        getContentPane().add(txt_nombre_gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 140, -1));

        jLabel23.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel23.setText("Correo:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        lbl_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subir (2).png"))); // NOI18N
        getContentPane().add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 140, 120));

        btn_caragarfoto.setFont(new java.awt.Font("Skrapbook", 0, 14)); // NOI18N
        btn_caragarfoto.setText("CARGAR");
        getContentPane().add(btn_caragarfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        btn_atras.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 620, 60, 40));

        jLabel24.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel24.setText("Nombre: ");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, -1));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 140, -1));

        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoPrincipal.png"))); // NOI18N
        getContentPane().add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gerente (3).png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 100, 130));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/veterinario (3).png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 150, 130));

        jLabel26.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel26.setText("Teléfono:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dinomik", 0, 23)); // NOI18N
        jLabel27.setText("Correo:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        txt_correo_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correo_gerenteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_correo_gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 140, -1));

        jLabel14.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel14.setText("Atras");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 640, -1, -1));

        btn_registrar.setFont(new java.awt.Font("Skrapbook", 0, 36)); // NOI18N
        btn_registrar.setText("REGISTRAR");
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoRegistroGE.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1080, 750));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_correo_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correo_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correo_gerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Reg_Establecimeinto_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Reg_Establecimeinto_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Reg_Establecimeinto_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Reg_Establecimeinto_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Reg_Establecimeinto_Gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_atras;
    private javax.swing.JButton btn_caragarfoto;
    private javax.swing.JLabel btn_inicio;
    private javax.swing.JLabel btn_registrar;
    private javax.swing.JCheckBox cb_accesorio;
    private javax.swing.JCheckBox cb_medicina;
    private javax.swing.JCheckBox cb_peluqueria;
    private javax.swing.JComboBox<String> cbx_hora_apertura;
    private javax.swing.JComboBox<String> cbx_hora_apertura_numero;
    private javax.swing.JComboBox<String> cbx_hora_cierre;
    private javax.swing.JComboBox<String> cbx_hora_cierre_numero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner js_nuemro;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_correo_gerente;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre_gerente;
    private javax.swing.JTextField txt_sector;
    private javax.swing.JTextField txt_telefono_esta;
    private javax.swing.JTextField txt_telefono_gerente;
    // End of variables declaration//GEN-END:variables
}
