/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author ACER
 */
public class frm_establecimiento extends javax.swing.JFrame {

    /**
     * Creates new form frm_establecimiento
     */
    public frm_establecimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg_citas_registradas = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_citas_reg = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        txt_busc_cedula = new javax.swing.JTextField();
        btn_atras_cit_reg = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dlg_generar_cita = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_cedu_regi_cita = new javax.swing.JTextField();
        txt_apellido_dlgregicita = new javax.swing.JTextField();
        cbxhora_dlgregicita = new javax.swing.JComboBox<>();
        cbx_ampm_dlgregicita = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btn_registrarcita_dlgregicita = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txt_nombre_dlgregicita = new javax.swing.JTextField();
        fondodlg = new javax.swing.JLabel();
        dlg_reg_emple = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        cbx_genero_dlgregemple = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_apellido_dlgregemple = new javax.swing.JTextField();
        txt_cedula_dlgregemple = new javax.swing.JTextField();
        txt_telef_dlgregemple = new javax.swing.JTextField();
        txt_correo_dlgregemple = new javax.swing.JTextField();
        txt_cargo_dlgregemple = new javax.swing.JTextField();
        txt_anios_dlgregemple = new javax.swing.JTextField();
        txt_nombre_dlgregemple = new javax.swing.JTextField();
        btn_atras_dlgregemple = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btn_registrar_dlgregemple = new javax.swing.JLabel();
        fondo_dlgemp = new javax.swing.JLabel();
        dlg_reg_mascota = new javax.swing.JDialog();
        jLabel48 = new javax.swing.JLabel();
        lbl_foto_dlgregmasco = new javax.swing.JLabel();
        btn_atras_dlgregmasco = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txt_vacu_dlgregmasco = new javax.swing.JTextField();
        txt_desc_dlgregmasco = new javax.swing.JTextField();
        txt_nombre_dlgregmasco = new javax.swing.JTextField();
        btn_cargar_dlgregmasco = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        btn_registrar_dlgregmasco = new javax.swing.JLabel();
        cbx_sexo_dlgregmasco = new javax.swing.JComboBox<>();
        cbx_raza_dlgregmasco = new javax.swing.JComboBox<>();
        fondo_dlgregmas = new javax.swing.JLabel();
        Dialogo_producto = new javax.swing.JDialog();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        txt_idproducto_dialogo_producto = new javax.swing.JTextField();
        txt_nombre_dialogo_producto = new javax.swing.JTextField();
        txt_precio_dialogo_producto = new javax.swing.JTextField();
        txt_descripcion_dialogo_producto = new javax.swing.JTextField();
        txt_tipo_dialogo_producto = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        btn_atras_dialogo_regisproducto = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        lbl_fot_regis_producto_dialogo_producto = new javax.swing.JLabel();
        btn_cargar_imagen_dialogo_producto = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        dialogo_publicidad = new javax.swing.JDialog();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        lbl_ft1_publicidad_dialogo_Editar_Publicidad = new javax.swing.JLabel();
        lbl_ft2_publicidad_publicidad_dialogo_Editar_Publicidad = new javax.swing.JLabel();
        lbl_ft3_publicidad_publicidad_dialogo_Editar_Publicidad = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        btn_atras_dialogo_publicidad = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_Area_dialogo_descripcion = new javax.swing.JTextArea();
        jLabel82 = new javax.swing.JLabel();
        dialogo_accesorios = new javax.swing.JDialog();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_atras_dialogo_Accesorios = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_Accesorios_Dialogo_accesorios = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dialogo_adopcion = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabla_adopcion_dialogo_adopcion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        btn_atras_dialogo_Adopcion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_perro_macho_dialogo_Adopcion = new javax.swing.JLabel();
        btn_perro_hembra_Dialogo_adopcion = new javax.swing.JLabel();
        btn_raza_grande_Dialogo_Adopcion = new javax.swing.JLabel();
        btn_raza_pequeña_Dialogo_Adopcion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_foto_publi_estab = new javax.swing.JLabel();
        lbl_nombre_establ = new javax.swing.JLabel();
        lbl_logo_estable = new javax.swing.JLabel();
        lbl_fotos_establ = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_telef = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_direccion_estable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_empleados = new javax.swing.JTable();
        lbl_descrip_estable = new javax.swing.JLabel();
        btn_ver_adopciones = new javax.swing.JLabel();
        btn_ver_produ = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_iragendar_cita = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_atras_estable = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_establecimiento = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnu_usuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnu_reg_mascota = new javax.swing.JMenuItem();
        mnu_reg_produ = new javax.swing.JMenuItem();
        mnu_reg_emple = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnu_editar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnu_cerrar_sesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        dlg_citas_registradas.setMinimumSize(new java.awt.Dimension(660, 470));
        dlg_citas_registradas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_citas_reg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_citas_reg);

        dlg_citas_registradas.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 480, 270));

        jLabel19.setFont(new java.awt.Font("Honey and Raspberries", 0, 24)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/026-report.png"))); // NOI18N
        jLabel19.setText("CITAS REGISTRADAS");
        jLabel19.setToolTipText("Agendar Cita");
        dlg_citas_registradas.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        txt_busc_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busc_cedulaActionPerformed(evt);
            }
        });
        dlg_citas_registradas.getContentPane().add(txt_busc_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, -1));

        btn_atras_cit_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        dlg_citas_registradas.getContentPane().add(btn_atras_cit_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 60, 40));

        jLabel21.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel21.setText("Atras");
        dlg_citas_registradas.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_dialogo_citasregi.png"))); // NOI18N
        dlg_citas_registradas.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        dlg_generar_cita.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        dlg_generar_cita.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 60, 40));

        jLabel24.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel24.setText("Atras");
        dlg_generar_cita.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        jLabel25.setFont(new java.awt.Font("Honey and Raspberries", 0, 24)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/026-report.png"))); // NOI18N
        jLabel25.setText("REGISTRAR UNA CITA");
        jLabel25.setToolTipText("Agendar Cita");
        dlg_generar_cita.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        txt_cedu_regi_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedu_regi_citaActionPerformed(evt);
            }
        });
        dlg_generar_cita.getContentPane().add(txt_cedu_regi_cita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 20));
        dlg_generar_cita.getContentPane().add(txt_apellido_dlgregicita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 20));

        cbxhora_dlgregicita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00" }));
        cbxhora_dlgregicita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxhora_dlgregicitaActionPerformed(evt);
            }
        });
        dlg_generar_cita.getContentPane().add(cbxhora_dlgregicita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 90, -1));

        cbx_ampm_dlgregicita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "am", "pm" }));
        dlg_generar_cita.getContentPane().add(cbx_ampm_dlgregicita, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 50, -1));

        jLabel22.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel22.setText("Apelllido");
        dlg_generar_cita.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel26.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel26.setText("Fecha");
        dlg_generar_cita.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel27.setText("Hora de atencion");
        dlg_generar_cita.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel28.setText("Cedula");
        dlg_generar_cita.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btn_registrarcita_dlgregicita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/014-health-report.png"))); // NOI18N
        btn_registrarcita_dlgregicita.setToolTipText("Generar Cita");
        dlg_generar_cita.getContentPane().add(btn_registrarcita_dlgregicita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 80, 90));

        jLabel46.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel46.setText("Nombre");
        dlg_generar_cita.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        dlg_generar_cita.getContentPane().add(txt_nombre_dlgregicita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 20));

        fondodlg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_dialogo_citasregi.png"))); // NOI18N
        dlg_generar_cita.getContentPane().add(fondodlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        dlg_reg_emple.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/030-veterinarian-HOMBRE.png"))); // NOI18N
        dlg_reg_emple.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel32.setFont(new java.awt.Font("Honey and Raspberries", 0, 36)); // NOI18N
        jLabel32.setText("<HTML>REGISTRAR<BR> EMPLEADO");
        dlg_reg_emple.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/020-veterinarian,MUJER.png"))); // NOI18N
        dlg_reg_emple.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel34.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel34.setText("Cedula");
        dlg_reg_emple.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        cbx_genero_dlgregemple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        dlg_reg_emple.getContentPane().add(cbx_genero_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 90, -1));

        jLabel35.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Nombre");
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dlg_reg_emple.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel36.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel36.setText("Telefono");
        dlg_reg_emple.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel37.setText("Correo");
        dlg_reg_emple.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel38.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel38.setText("Genero");
        dlg_reg_emple.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jLabel39.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel39.setText("Cargo");
        dlg_reg_emple.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel40.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel40.setText("Apellido");
        dlg_reg_emple.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel41.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel41.setText("<html>Fecha de<br>nacimiento");
        dlg_reg_emple.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel42.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel42.setText("<html>Años <br>trabajados");
        dlg_reg_emple.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));
        dlg_reg_emple.getContentPane().add(txt_apellido_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, -1));
        dlg_reg_emple.getContentPane().add(txt_cedula_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, -1));
        dlg_reg_emple.getContentPane().add(txt_telef_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 150, -1));
        dlg_reg_emple.getContentPane().add(txt_correo_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 150, -1));
        dlg_reg_emple.getContentPane().add(txt_cargo_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 150, -1));
        dlg_reg_emple.getContentPane().add(txt_anios_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 150, -1));

        txt_nombre_dlgregemple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre_dlgregemple.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dlg_reg_emple.getContentPane().add(txt_nombre_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 150, -1));

        btn_atras_dlgregemple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        dlg_reg_emple.getContentPane().add(btn_atras_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 60, 40));

        jLabel43.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel43.setText("Atras");
        dlg_reg_emple.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        btn_registrar_dlgregemple.setFont(new java.awt.Font("Kiddos", 1, 24)); // NOI18N
        btn_registrar_dlgregemple.setText("REGISTRAR");
        dlg_reg_emple.getContentPane().add(btn_registrar_dlgregemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        fondo_dlgemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_dlg_regempleado.png"))); // NOI18N
        dlg_reg_emple.getContentPane().add(fondo_dlgemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dlg_reg_mascota.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel48.setText("Raza");
        dlg_reg_mascota.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        lbl_foto_dlgregmasco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subir (2).png"))); // NOI18N
        dlg_reg_mascota.getContentPane().add(lbl_foto_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        btn_atras_dlgregmasco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        dlg_reg_mascota.getContentPane().add(btn_atras_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 60, 40));

        jLabel51.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel51.setText("Atras");
        dlg_reg_mascota.getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        jLabel52.setFont(new java.awt.Font("Honey and Raspberries", 0, 36)); // NOI18N
        jLabel52.setText("<HTML>REGISTRAR<BR> MASCOTA");
        dlg_reg_mascota.getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jLabel53.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel53.setText("Sexo");
        dlg_reg_mascota.getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel54.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel54.setText("Vacunas");
        dlg_reg_mascota.getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel55.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel55.setText("Descripcion");
        dlg_reg_mascota.getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel56.setFont(new java.awt.Font("Dinomik", 0, 18)); // NOI18N
        jLabel56.setText("Nombre");
        dlg_reg_mascota.getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/029-dog.png"))); // NOI18N
        dlg_reg_mascota.getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        txt_vacu_dlgregmasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vacu_dlgregmascoActionPerformed(evt);
            }
        });
        dlg_reg_mascota.getContentPane().add(txt_vacu_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 20));

        txt_desc_dlgregmasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_dlgregmascoActionPerformed(evt);
            }
        });
        dlg_reg_mascota.getContentPane().add(txt_desc_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, 20));

        txt_nombre_dlgregmasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_dlgregmascoActionPerformed(evt);
            }
        });
        dlg_reg_mascota.getContentPane().add(txt_nombre_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, 20));

        btn_cargar_dlgregmasco.setFont(new java.awt.Font("Skrapbook", 1, 14)); // NOI18N
        btn_cargar_dlgregmasco.setText("CARGAR FOTO");
        btn_cargar_dlgregmasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargar_dlgregmascoActionPerformed(evt);
            }
        });
        dlg_reg_mascota.getContentPane().add(btn_cargar_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/033-house.png"))); // NOI18N
        dlg_reg_mascota.getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        btn_registrar_dlgregmasco.setFont(new java.awt.Font("Kiddos", 0, 24)); // NOI18N
        btn_registrar_dlgregmasco.setText("REGISTRAR");
        dlg_reg_mascota.getContentPane().add(btn_registrar_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        cbx_sexo_dlgregmasco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));
        dlg_reg_mascota.getContentPane().add(cbx_sexo_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, -1));

        cbx_raza_dlgregmasco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Pequeña" }));
        dlg_reg_mascota.getContentPane().add(cbx_raza_dlgregmasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 90, -1));

        fondo_dlgregmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_reg_mascota.png"))); // NOI18N
        dlg_reg_mascota.getContentPane().add(fondo_dlgregmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 400));

        Dialogo_producto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Honey and Raspberries", 2, 36)); // NOI18N
        jLabel69.setText("REGISTAR PRODUCTO ");
        Dialogo_producto.getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perrito_rproducto_preview_rev_1.png"))); // NOI18N
        Dialogo_producto.getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 80));

        jLabel29.setFont(new java.awt.Font("Dinomik", 2, 18)); // NOI18N
        jLabel29.setText("NOMBRE");
        Dialogo_producto.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dinomik", 2, 18)); // NOI18N
        jLabel30.setText("PRECIO");
        Dialogo_producto.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, 20));

        jLabel71.setFont(new java.awt.Font("Dinomik", 2, 18)); // NOI18N
        jLabel71.setText("DESCRIPCION");
        Dialogo_producto.getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, -1));

        jLabel72.setFont(new java.awt.Font("Dinomik", 2, 18)); // NOI18N
        jLabel72.setText("ID_PRODUCTO");
        Dialogo_producto.getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel73.setFont(new java.awt.Font("Dinomik", 2, 18)); // NOI18N
        jLabel73.setText("TIPO");
        Dialogo_producto.getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 150, 20));
        Dialogo_producto.getContentPane().add(txt_idproducto_dialogo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 120, 20));
        Dialogo_producto.getContentPane().add(txt_nombre_dialogo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 120, -1));

        txt_precio_dialogo_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precio_dialogo_productoActionPerformed(evt);
            }
        });
        Dialogo_producto.getContentPane().add(txt_precio_dialogo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, -1));
        Dialogo_producto.getContentPane().add(txt_descripcion_dialogo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 120, -1));
        Dialogo_producto.getContentPane().add(txt_tipo_dialogo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 120, -1));

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_adopcion.png"))); // NOI18N
        jLabel74.setText("jLabel34");
        Dialogo_producto.getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 370, 120, 70));

        btn_atras_dialogo_regisproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        Dialogo_producto.getContentPane().add(btn_atras_dialogo_regisproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 60, 40));

        jLabel75.setFont(new java.awt.Font("Kiddos", 2, 18)); // NOI18N
        jLabel75.setText("ATRAS");
        Dialogo_producto.getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 50, 20));

        lbl_fot_regis_producto_dialogo_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subir (2)_1.png"))); // NOI18N
        lbl_fot_regis_producto_dialogo_producto.setText("foto producto");
        Dialogo_producto.getContentPane().add(lbl_fot_regis_producto_dialogo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 130, 140));

        btn_cargar_imagen_dialogo_producto.setFont(new java.awt.Font("Honey and Raspberries", 2, 18)); // NOI18N
        btn_cargar_imagen_dialogo_producto.setText("CARGAR IMAGEN  ");
        Dialogo_producto.getContentPane().add(btn_cargar_imagen_dialogo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos_dialogos.png"))); // NOI18N
        Dialogo_producto.getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        dialogo_publicidad.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setFont(new java.awt.Font("Kiddos", 2, 36)); // NOI18N
        jLabel77.setText("EDITAR PUBLICIDAD ");
        dialogo_publicidad.getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 260, 50));

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perrito_publicidad_preview_rev_1.png"))); // NOI18N
        dialogo_publicidad.getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 70, 70));

        lbl_ft1_publicidad_dialogo_Editar_Publicidad.setBackground(new java.awt.Color(153, 204, 255));
        lbl_ft1_publicidad_dialogo_Editar_Publicidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subir (2).png"))); // NOI18N
        lbl_ft1_publicidad_dialogo_Editar_Publicidad.setText("foto publicidad");
        dialogo_publicidad.getContentPane().add(lbl_ft1_publicidad_dialogo_Editar_Publicidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 130, 300));

        lbl_ft2_publicidad_publicidad_dialogo_Editar_Publicidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subir (2).png"))); // NOI18N
        dialogo_publicidad.getContentPane().add(lbl_ft2_publicidad_publicidad_dialogo_Editar_Publicidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 160, 300));

        lbl_ft3_publicidad_publicidad_dialogo_Editar_Publicidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subir (2).png"))); // NOI18N
        dialogo_publicidad.getContentPane().add(lbl_ft3_publicidad_publicidad_dialogo_Editar_Publicidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 150, 290));

        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_adopcion.png"))); // NOI18N
        dialogo_publicidad.getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 590, 130, 80));

        btn_atras_dialogo_publicidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        dialogo_publicidad.getContentPane().add(btn_atras_dialogo_publicidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 60, 50));

        jLabel80.setFont(new java.awt.Font("Kiddos", 2, 18)); // NOI18N
        jLabel80.setText("ATRAS");
        dialogo_publicidad.getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, 40, 20));

        jLabel81.setFont(new java.awt.Font("Honey and Raspberries", 0, 18)); // NOI18N
        jLabel81.setText("DESCRIPCION");
        dialogo_publicidad.getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 110, 30));

        txt_Area_dialogo_descripcion.setColumns(20);
        txt_Area_dialogo_descripcion.setLineWrap(true);
        txt_Area_dialogo_descripcion.setRows(5);
        txt_Area_dialogo_descripcion.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txt_Area_dialogo_descripcion);

        dialogo_publicidad.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 350, 70));

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDO2.png"))); // NOI18N
        jLabel82.setText("jLabel39");
        dialogo_publicidad.getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 660, 680));

        dialogo_accesorios.setMinimumSize(new java.awt.Dimension(660, 470));
        dialogo_accesorios.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel83.setFont(new java.awt.Font("Honey and Raspberries", 2, 36)); // NOI18N
        jLabel83.setText("Si Quieres Concentirlos ");
        dialogo_accesorios.getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 380, 60));

        jLabel84.setFont(new java.awt.Font("Honey and Raspberries", 2, 36)); // NOI18N
        jLabel84.setText("Este es el lugar!!");
        dialogo_accesorios.getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 350, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_adopcion.png"))); // NOI18N
        dialogo_accesorios.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 380, 130, 70));

        btn_atras_dialogo_Accesorios.setFont(new java.awt.Font("Kiddos", 2, 24)); // NOI18N
        btn_atras_dialogo_Accesorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        btn_atras_dialogo_Accesorios.setToolTipText("");
        dialogo_accesorios.getContentPane().add(btn_atras_dialogo_Accesorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 60, 50));

        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla_productos_preview_rev_1.png"))); // NOI18N
        dialogo_accesorios.getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 90, 60));

        tbl_Accesorios_Dialogo_accesorios.setBackground(new java.awt.Color(153, 204, 255));
        tbl_Accesorios_Dialogo_accesorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PRODUCTO", "PRECIO", "FOTO"
            }
        ));
        jScrollPane6.setViewportView(tbl_Accesorios_Dialogo_accesorios);

        dialogo_accesorios.getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 550, 130));

        jLabel16.setFont(new java.awt.Font("Kiddos", 2, 18)); // NOI18N
        jLabel16.setText("ATRAS");
        dialogo_accesorios.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        jLabel86.setFont(new java.awt.Font("Honey and Raspberries", 2, 24)); // NOI18N
        jLabel86.setText("ACCESORIOS");
        dialogo_accesorios.getContentPane().add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 130, 30));

        jLabel12.setText("COMESTIBLES");
        dialogo_accesorios.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel13.setText("No comestibles");
        dialogo_accesorios.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos_dialogos.png"))); // NOI18N
        dialogo_accesorios.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 690, 490));

        dialogo_adopcion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_adopcion_dialogo_adopcion.setBackground(new java.awt.Color(207, 229, 235));
        tabla_adopcion_dialogo_adopcion.setFont(new java.awt.Font("Kiddos", 2, 18)); // NOI18N
        tabla_adopcion_dialogo_adopcion.setForeground(new java.awt.Color(255, 255, 255));
        tabla_adopcion_dialogo_adopcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMBRE", "EDAD", "VACUNAS", "FOTO"
            }
        ));
        jScrollPane7.setViewportView(tabla_adopcion_dialogo_adopcion);

        dialogo_adopcion.getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 540, 170));

        jLabel1.setFont(new java.awt.Font("Honey and Raspberries", 2, 36)); // NOI18N
        jLabel1.setText("ENCUENTRA ");
        dialogo_adopcion.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 200, -1));

        jLabel87.setFont(new java.awt.Font("Honey and Raspberries", 1, 36)); // NOI18N
        jLabel87.setText("A TU AMIGO PELUDO ");
        dialogo_adopcion.getContentPane().add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 330, 50));

        btn_atras_dialogo_Adopcion.setFont(new java.awt.Font("Kiddos", 2, 14)); // NOI18N
        btn_atras_dialogo_Adopcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        btn_atras_dialogo_Adopcion.setToolTipText("VOLVER AL INICIO ");
        dialogo_adopcion.getContentPane().add(btn_atras_dialogo_Adopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 70, 40));

        jLabel6.setFont(new java.awt.Font("Kiddos", 2, 18)); // NOI18N
        jLabel6.setText("ATRAS");
        dialogo_adopcion.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 50, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_adopcion.png"))); // NOI18N
        dialogo_adopcion.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 380, 120, 80));

        jLabel10.setFont(new java.awt.Font("Kiddos", 1, 18)); // NOI18N
        jLabel10.setText("Filtros de Busqueda");
        dialogo_adopcion.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        btn_perro_macho_dialogo_Adopcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/macho.png"))); // NOI18N
        btn_perro_macho_dialogo_Adopcion.setToolTipText("Machos");
        dialogo_adopcion.getContentPane().add(btn_perro_macho_dialogo_Adopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 40, 40));

        btn_perro_hembra_Dialogo_adopcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hembra.png"))); // NOI18N
        btn_perro_hembra_Dialogo_adopcion.setToolTipText("Hembras");
        dialogo_adopcion.getContentPane().add(btn_perro_hembra_Dialogo_adopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 40));

        btn_raza_grande_Dialogo_Adopcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/razagrande.png"))); // NOI18N
        btn_raza_grande_Dialogo_Adopcion.setToolTipText("raza grande");
        dialogo_adopcion.getContentPane().add(btn_raza_grande_Dialogo_Adopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 40, 30));

        btn_raza_pequeña_Dialogo_Adopcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/razapequeña.png"))); // NOI18N
        btn_raza_pequeña_Dialogo_Adopcion.setToolTipText("raza pequeña");
        dialogo_adopcion.getContentPane().add(btn_raza_pequeña_Dialogo_Adopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 30, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos_dialogos.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        dialogo_adopcion.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_foto_publi_estab.setText("publicidad");
        getContentPane().add(lbl_foto_publi_estab, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 140, 590));

        lbl_nombre_establ.setFont(new java.awt.Font("Honey and Raspberries", 0, 24)); // NOI18N
        lbl_nombre_establ.setText("NOMBRE DEL ESTABLECIMIENTO");
        getContentPane().add(lbl_nombre_establ, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 300, 30));

        lbl_logo_estable.setText("LOGO");
        getContentPane().add(lbl_logo_estable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 90));

        lbl_fotos_establ.setText("imagenes");
        getContentPane().add(lbl_fotos_establ, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 450, 240));

        jLabel4.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel4.setText("EMPLEADOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Skrapbook", 1, 12)); // NOI18N
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lbl_telef.setFont(new java.awt.Font("Skrapbook", 0, 14)); // NOI18N
        lbl_telef.setText("jLabel4");
        getContentPane().add(lbl_telef, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Skrapbook", 1, 12)); // NOI18N
        jLabel7.setText("Correo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        lbl_correo.setFont(new java.awt.Font("Skrapbook", 0, 14)); // NOI18N
        lbl_correo.setText("jLabel4");
        getContentPane().add(lbl_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Skrapbook", 1, 12)); // NOI18N
        jLabel9.setText("Direccion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        lbl_direccion_estable.setFont(new java.awt.Font("Skrapbook", 0, 14)); // NOI18N
        lbl_direccion_estable.setText("jLabel4");
        getContentPane().add(lbl_direccion_estable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        tbl_empleados.setBackground(new java.awt.Color(234, 152, 93));
        tbl_empleados.setForeground(new java.awt.Color(234, 152, 93));
        tbl_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_empleados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 190, 240));

        lbl_descrip_estable.setText("descripcion");
        getContentPane().add(lbl_descrip_estable, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 440, 70));

        btn_ver_adopciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/veterinario.png"))); // NOI18N
        btn_ver_adopciones.setToolTipText("Mostrar perros en adopcion");
        getContentPane().add(btn_ver_adopciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 70, 80));

        btn_ver_produ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/006-collar.png"))); // NOI18N
        btn_ver_produ.setToolTipText("Ver accesorios disponibles");
        getContentPane().add(btn_ver_produ, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 70, 70));

        jLabel15.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel15.setText("CONTACTO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        btn_iragendar_cita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/026-report.png"))); // NOI18N
        btn_iragendar_cita.setToolTipText("Agendar Cita");
        getContentPane().add(btn_iragendar_cita, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Kiddos", 0, 18)); // NOI18N
        jLabel14.setText("Atras");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 650, -1, -1));

        btn_atras_estable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_atras.png"))); // NOI18N
        getContentPane().add(btn_atras_estable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 630, 60, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_princ_establecimiento.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 680));

        menu_establecimiento.setText("Menu");
        menu_establecimiento.add(jSeparator1);

        mnu_usuario.setText("Usuario");
        mnu_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_usuarioActionPerformed(evt);
            }
        });
        menu_establecimiento.add(mnu_usuario);
        menu_establecimiento.add(jSeparator2);

        mnu_reg_mascota.setText("Registrar Mascota");
        mnu_reg_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_reg_mascotaActionPerformed(evt);
            }
        });
        menu_establecimiento.add(mnu_reg_mascota);

        mnu_reg_produ.setText("Registrar Producto");
        menu_establecimiento.add(mnu_reg_produ);

        mnu_reg_emple.setText("Registrar Empleado");
        menu_establecimiento.add(mnu_reg_emple);
        menu_establecimiento.add(jSeparator3);

        mnu_editar.setText("Editar Informacion");
        menu_establecimiento.add(mnu_editar);
        menu_establecimiento.add(jSeparator4);
        menu_establecimiento.add(jSeparator5);

        mnu_cerrar_sesion.setText("Cerrar Sesion");
        mnu_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_cerrar_sesionActionPerformed(evt);
            }
        });
        menu_establecimiento.add(mnu_cerrar_sesion);

        jMenuBar1.add(menu_establecimiento);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnu_usuarioActionPerformed

    private void mnu_reg_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_reg_mascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnu_reg_mascotaActionPerformed

    private void mnu_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_cerrar_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnu_cerrar_sesionActionPerformed

    private void cbxhora_dlgregicitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxhora_dlgregicitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxhora_dlgregicitaActionPerformed

    private void txt_cedu_regi_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedu_regi_citaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedu_regi_citaActionPerformed

    private void txt_vacu_dlgregmascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vacu_dlgregmascoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vacu_dlgregmascoActionPerformed

    private void txt_desc_dlgregmascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_dlgregmascoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_dlgregmascoActionPerformed

    private void txt_nombre_dlgregmascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_dlgregmascoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_dlgregmascoActionPerformed

    private void btn_cargar_dlgregmascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargar_dlgregmascoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cargar_dlgregmascoActionPerformed

    private void txt_busc_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busc_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busc_cedulaActionPerformed

    private void txt_precio_dialogo_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precio_dialogo_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precio_dialogo_productoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_establecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_establecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_establecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_establecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_establecimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialogo_producto;
    private javax.swing.JLabel btn_atras_cit_reg;
    private javax.swing.JLabel btn_atras_dialogo_Accesorios;
    private javax.swing.JLabel btn_atras_dialogo_Adopcion;
    private javax.swing.JLabel btn_atras_dialogo_publicidad;
    private javax.swing.JLabel btn_atras_dialogo_regisproducto;
    private javax.swing.JLabel btn_atras_dlgregemple;
    private javax.swing.JLabel btn_atras_dlgregmasco;
    private javax.swing.JLabel btn_atras_estable;
    private javax.swing.JButton btn_cargar_dlgregmasco;
    private javax.swing.JLabel btn_cargar_imagen_dialogo_producto;
    private javax.swing.JLabel btn_iragendar_cita;
    private javax.swing.JLabel btn_perro_hembra_Dialogo_adopcion;
    private javax.swing.JLabel btn_perro_macho_dialogo_Adopcion;
    private javax.swing.JLabel btn_raza_grande_Dialogo_Adopcion;
    private javax.swing.JLabel btn_raza_pequeña_Dialogo_Adopcion;
    private javax.swing.JLabel btn_registrar_dlgregemple;
    private javax.swing.JLabel btn_registrar_dlgregmasco;
    private javax.swing.JLabel btn_registrarcita_dlgregicita;
    private javax.swing.JLabel btn_ver_adopciones;
    private javax.swing.JLabel btn_ver_produ;
    private javax.swing.JComboBox<String> cbx_ampm_dlgregicita;
    private javax.swing.JComboBox<String> cbx_genero_dlgregemple;
    private javax.swing.JComboBox<String> cbx_raza_dlgregmasco;
    private javax.swing.JComboBox<String> cbx_sexo_dlgregmasco;
    private javax.swing.JComboBox<String> cbxhora_dlgregicita;
    private javax.swing.JDialog dialogo_accesorios;
    private javax.swing.JDialog dialogo_adopcion;
    private javax.swing.JDialog dialogo_publicidad;
    private javax.swing.JDialog dlg_citas_registradas;
    private javax.swing.JDialog dlg_generar_cita;
    private javax.swing.JDialog dlg_reg_emple;
    private javax.swing.JDialog dlg_reg_mascota;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo_dlgemp;
    private javax.swing.JLabel fondo_dlgregmas;
    private javax.swing.JLabel fondodlg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_descrip_estable;
    private javax.swing.JLabel lbl_direccion_estable;
    private javax.swing.JLabel lbl_fot_regis_producto_dialogo_producto;
    private javax.swing.JLabel lbl_foto_dlgregmasco;
    private javax.swing.JLabel lbl_foto_publi_estab;
    private javax.swing.JLabel lbl_fotos_establ;
    private javax.swing.JLabel lbl_ft1_publicidad_dialogo_Editar_Publicidad;
    private javax.swing.JLabel lbl_ft2_publicidad_publicidad_dialogo_Editar_Publicidad;
    private javax.swing.JLabel lbl_ft3_publicidad_publicidad_dialogo_Editar_Publicidad;
    private javax.swing.JLabel lbl_logo_estable;
    private javax.swing.JLabel lbl_nombre_establ;
    private javax.swing.JLabel lbl_telef;
    private javax.swing.JMenu menu_establecimiento;
    private javax.swing.JMenuItem mnu_cerrar_sesion;
    private javax.swing.JMenuItem mnu_editar;
    private javax.swing.JMenuItem mnu_reg_emple;
    private javax.swing.JMenuItem mnu_reg_mascota;
    private javax.swing.JMenuItem mnu_reg_produ;
    private javax.swing.JMenuItem mnu_usuario;
    private javax.swing.JTable tabla_adopcion_dialogo_adopcion;
    private javax.swing.JTable tbl_Accesorios_Dialogo_accesorios;
    private javax.swing.JTable tbl_citas_reg;
    private javax.swing.JTable tbl_empleados;
    private javax.swing.JTextArea txt_Area_dialogo_descripcion;
    private javax.swing.JTextField txt_anios_dlgregemple;
    private javax.swing.JTextField txt_apellido_dlgregemple;
    private javax.swing.JTextField txt_apellido_dlgregicita;
    private javax.swing.JTextField txt_busc_cedula;
    private javax.swing.JTextField txt_cargo_dlgregemple;
    private javax.swing.JTextField txt_cedu_regi_cita;
    private javax.swing.JTextField txt_cedula_dlgregemple;
    private javax.swing.JTextField txt_correo_dlgregemple;
    private javax.swing.JTextField txt_desc_dlgregmasco;
    private javax.swing.JTextField txt_descripcion_dialogo_producto;
    private javax.swing.JTextField txt_idproducto_dialogo_producto;
    private javax.swing.JTextField txt_nombre_dialogo_producto;
    private javax.swing.JTextField txt_nombre_dlgregemple;
    private javax.swing.JTextField txt_nombre_dlgregicita;
    private javax.swing.JTextField txt_nombre_dlgregmasco;
    private javax.swing.JTextField txt_precio_dialogo_producto;
    private javax.swing.JTextField txt_telef_dlgregemple;
    private javax.swing.JTextField txt_tipo_dialogo_producto;
    private javax.swing.JTextField txt_vacu_dlgregmasco;
    // End of variables declaration//GEN-END:variables
}
